parameters:
    cronjobs:
        processUserScores:
            command: owt:processUserScores
            interval: 10
        readDemoInfo:
            command: rabbitmq:consumer
            arguments:
                - demo_info_upload
            options:
                - -m 10
            interval: 2