parameters:
    database_host: localhost
    database_port: null
    database_name: overwatch
    database_user: root
    database_password: test123
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null

    secret: jUZofDIm3TfGJuppgCBYD5USPvLn0BGivsO2

    mongo_server: mongodb://localhost:27017
    mongo_database: owt

    memcache.servers:
        - { host: 127.0.0.1, port: 11211 }

    session_memcache_host: localhost
    session_memcache_port: 11211
    session_memcache_prefix: sess
    session_memcache_expire: 3600

imports:
    - { resource: cronjobs.yml }
