app:
    resource: "@AppBundle/Controller/"
    type:     annotation
user:
    resource: "@UserBundle/Controller/"
    type:     annotation
overwatch:
    resource: "@OverwatchBundle/Controller/"
    type:     annotation
admin_stats:
    resource: "@AdminStatsBundle/Controller/"
    type:     annotation